posts/urls.py
from django.urls import path
from .views import (
    post_create,
    load_post_data_view,
    like_unlike_post_view,
    post_detail,
    post_detail_data_view,
    update_post,
    delete_post,
    image_upload_view
)

app_name = 'posts'

urlpatterns = [
    path('',post_create, name='post-list'),
    path('data/<int:num_posts>',load_post_data_view, name='post-data'),
    path('like-unlike/',like_unlike_post_view, name='like-unlike'),
    path('upload-image/',image_upload_view, name='image-upload'),

    path('post-detail/<int:pk>',post_detail, name='post-detail'),
    path('post-detail/data/<int:pk>',post_detail_data_view, name='post-detail-data'),
    path('post-detail/update/<int:pk>',update_post, name='post-update'),
    path('post-detail/delete/<int:pk>',delete_post, name='post-delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.AdminSite.site_title = "DJ-AJAX | Admin"
admin.AdminSite.site_header = "Admin Panel"
admin.AdminSite.index_title = "Django-ajax"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

urlpatterns += static(settings.STATIC_URL , doument_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    liked = models.ManyToManyField(User , blank=True)
    author = models.ForeignKey(Profile , on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.title}"
    
    @property
    def like_count(self):
        return self.liked.all().count()
    
    @property
    def get_photos(self):
        return self.photo.all()

    class Meta:
        ordering = ("-created_at",)


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="photo")
    image = models.ImageField(upload_to="photos")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post.title} - {self.pk}"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(default='default.png', 
            upload_to ='profile_pictures/')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Profile - {self.user.username}"

posts/forms.py
from django import forms 
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = [
            "title",
            "body"
        ]

posts/views.py
from django.http import HttpResponse, JsonResponse, HttpRequest
from django.shortcuts import render
from .models import Photo, Post
from .forms import PostForm
from profiles.models import Profile

# Create your views here.

def post_create(request):
    form = PostForm(request.POST or None)


    if request.is_ajax():
        if form.is_valid():
            author = Profile.objects.get(user=request.user)
            instance = form.save(commit=False)
            instance.author = author
            instance.save()
            return JsonResponse({
                'title' : instance.title,
                'body' : instance.body,
                'author' : author.user.username,
                'id': instance.id
            })
    
    context = {
        "form": form
    }
    return render(request, 'posts/main.html' , context=context)

def load_post_data_view(request, **kwargs):
    if request.is_ajax():
        visible = 3
        upper = kwargs.get('num_posts')
        lower = upper - visible
        size = Post.objects.all().count()
        
        posts = Post.objects.select_related('author')\
                .prefetch_related('liked').all()[lower:upper]

        data = []
        for each in posts:
            data.append({
                'id' : each.id,
                'title' : each.title,
                'body' : each.body,
                'liked' : True if request.user in each.liked.all() else False,
                'count' : each.like_count,
                'author' : each.author.user.username
            })

        return JsonResponse({
                "data" : data,
                "size" : size
            })

def post_detail_data_view(request , pk):
    obj = Post.objects.filter(pk=pk).first()

    if obj:
        data = {
            'id' : obj.id,
            'title' : obj.title,
            'body' : obj.body,
            'author' : obj.author.user.username,
            'logged_in' : request.user.username
        }
        return JsonResponse({'data': data})

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    form = PostForm() 

    context ={
        'post' : post,
        'form' : form
    }
    return render(request , 'posts/detail.html', context=context)
    
def like_unlike_post_view(request):
    if request.is_ajax():
        pk = request.POST.get('pk')
        post_obj = Post.objects.filter(pk = pk).first()

        if post_obj and request.user in post_obj.liked.all():
            liked = False
            post_obj.liked.remove(request.user)
        elif post_obj:
            liked = True 
            post_obj.liked.add(request.user)
        
        return JsonResponse({
            'liked' : liked,
            'count' : post_obj.like_count
        })


def update_post(request,pk):
    post = Post.objects.filter(pk=pk).first()
    if post:
        if request.is_ajax():
            post.title = request.POST.get('title')
            post.body = request.POST.get('body')
            post.save()
        return JsonResponse({
            'title' : post.title,
            'body' : post.body
        })
    return JsonResponse({})


def delete_post(request,pk):
    post = Post.objects.filter(pk=pk).first()
    if post:
        if request.is_ajax():
            post.delete()

    return JsonResponse({})


def image_upload_view(request):
    if request.method == "POST":
        image = request.FILES.get('file')
        new_post_id = request.POST.get('new_post_id')
        post = Post.objects.filter(id = new_post_id).first()
        if post:
            Photo.objects.create(image=image, post=post)
    
    return HttpResponse

profiles/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block script %}
    <script src="{% static 'posts/detail.js' %}" defer></script>
{% endblock %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}

    <!-- Update Modal -->
    <div
        class="modal fade"
        id="updateModal"
        tabindex="-1"
        aria-labelledby="updateLabel"
        aria-hidden="true"
    >
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="updateLabel">Update Post</h5>
            <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
            >
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert-box"></div>
            <form action="" id="update-form">
                {% csrf_token %}
                {{form|crispy}}

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        close
                    </button>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
        
        </div>
    </div>
    </div>


    <!-- Update Modal -->
    <div
        class="modal fade"
        id="deleteModal"
        tabindex="-1"
        aria-labelledby="deleteLabel"
        aria-hidden="true"
    >
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="deleteLabel">Delete Post</h5>
            <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close"
            >
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div id="alert-box"></div>
            <form action="" id="delete-form">
                {% csrf_token %}
                Are you sure you want to delete <b>{{post.title}} ?</b>  
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        close
                    </button>
                    <button type="submit" class="btn btn-primary">Delete</button>
                </div>
            </form>
        </div>
        
        </div>
    </div>
    </div>

    <button id="back-btn" class="btn btn-info">Home</button>
    <button id="update-btn" class="btn btn-info not-visible" data-toggle="modal" data-target="#updateModal">Update</button>
    <button id="delete-btn" class="btn btn-info not-visible" data-toggle="modal" data-target="#deleteModal">Delete</button>


    <div id="spinner-box" class="text-center">
        <div class="spinner-border" role="status"></div>
    </div>

    <!-- carosel -->
    {% if post.get_photos %}
    <div id="carouselExampleControls" class="carousel slide mt-2" data-ride="carousel">
        <div class="carousel-inner">
            {% for photo in post.get_photos %}
                <div 
                    class="carousel-item 
                        {% if forloop.counter == 1 %} active {% endif %}    
                    "
                >
                    <img src="{{photo.image.url}}" class="d-block w-100" alt="{{post.title}}" style="object-fit:cover;
                    object-position: right;
                   width:100%;
                   height:300px;">
                </div>
            {% endfor %}
        
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      {% endif%}
    <div id="post-box"></div>

{% endblock %}

posts/templates/posts/main.html
{% extends "base.html" %}
{% load static %} 
{% load crispy_forms_tags %}

{% block script %}
    <script src="{% static 'posts/main.js' %}" defer></script>
{% endblock %}

{% block title %} Posts {% endblock %} 

{% block content %}
    <div id="alert-box"></div>
    <!-- Modal -->
    <div
        class="modal fade"
        id="addPostModal"
        tabindex="-1"
        aria-labelledby="addPostLabel"
        aria-hidden="true"
    >
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="addPostLabel">Create Post</h5>
            <button
                type="button"
                class="close add-modal-close"
                data-dismiss="modal"
                aria-label="Close"
            >
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form action="" id="post-form">
                {% csrf_token %}
                {{form|crispy}}

                <div class="modal-footer">
                    <button type="button" class="btn btn-danger add-modal-close" data-dismiss="modal">
                        close
                    </button>
                    <button type="submit" class="btn btn-primary" id="add-btn">add</button>
                </div>
            </form>

            <form action="{% url 'posts:image-upload' %}" class="dz dropzone not-visible">
                  <div class="fallback">
                    <input name="file" type="file" multiple />
                  </div>
            </form>
                

        </div>
        
        </div>
    </div>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-info mb-2" data-toggle="modal" data-target="#addPostModal">
        Add Post
    </button>

    <div id="posts-box"></div>

    <div id="spinner-box" class="text-center">
    <div class="spinner-border" role="status"></div>
    </div>

    <div class="text-center mb-3" id="end-box">
    <button class="btn btn-success" id="load-btn">Load More</button>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap_min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    
    <!-- dropzone -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom JS -->
    <script src="{% static 'functions.js' %}" defer></script>

    {% block script %}
    {% endblock %}

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    
    <div class="container mt-3 ">
    {% block content %}
    {% endblock %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'jquery.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>